version: '3'
services:
  judge:
    build: .
    cap_add:
     - SYS_PTRACE
    volumes:
      - ./problems/:/problems/
      - ./judge.yml:/judge.yml
      - ./entry:/judge/.docker/entry
    restart: always
    image: judge
    ports:
      - 9995:9998
    environment:
      - IP=__IP__
      - PORT=__PORT__
      - JUDGE_YML=/judge.yml
